# .github/workflows/ci.yml
name: CI Pipeline

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - '*'
  push:
    branches:
      - master

env:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  pipeline:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build -restore --configuration ${{ env.buildConfiguration }}

      - name: Run Tests
        run: |
          dotnet test --logger "trx;logfilename=TestResults.trx" --no-build --configuration ${{ env.buildConfiguration }} --collect "XPlat Code Coverage;Format=opencover,cobertura"
        continue-on-error: false

      - name: SonqrQube Analyze
      - uses: sonarsource/sonarcloud-github-action@4.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
