# .github/workflows/ci.yml
name: CI Pipeline

on:
  workflow_dispatch:
  pull_request_target: # Runs for PRs, including from forks
    branches:
      - '*'
  push:
    branches:
      - master # This ensures the workflow also runs on master pushes

env:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  pipeline:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          ref: ${{ github.head_ref }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build -restore --configuration ${{ env.buildConfiguration }}

      - name: Run Tests
        run: |
          dotnet test --logger "trx;logfilename=TestResults.trx" --no-build --configuration ${{ env.buildConfiguration }} --collect "XPlat Code Coverage;Format=opencover,cobertura"
        continue-on-error: false

      - name: Publish Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage.cobertura.xml